/**
 * Auto-generated by scripts/generate-api-client.sh from the FastAPI
 * OpenAPI schema. Edit the script, not this file.
 *
 * In v1 we keep this as a hand-maintained re-export of types from
 * apps/web/src/lib/api-client.ts so the front-end and the API stay
 * in lockstep. Replace this file with the generated output once the
 * codegen pipeline is stable.
 */
export type {
  AuditEventOut,
  AuditPage,
  CredentialOut,
  MailboxOut,
  SignupInput,
  TenantOut,
  TokenPair,
  UserOut,
} from "../../../apps/web/src/lib/api-client";
