"""MeetingService \u2014 propose / confirm / decline / cancel a meeting.

Lifecycle:
    ReplyService._classify_and_act (positive)
        \u2193
    create_proposal()   \u2192 3 slots, status=proposed
        \u2193 (counter-reply OR manual POST /v1/meetings/{id}/confirm)
    confirm(slot_index) \u2192 calendar event created, status=confirmed
        \u2193 (decline/cancel API)
    decline() / cancel() \u2192 status=declined/cancelled

The scheduling logic is deliberately minimal in V1: the user picks a slot
on confirmation. The LLM-based slot extraction (parsing "Tuesday at 2pm")
lives in ReplyService and is keyed off `meeting.proposed_slots` to match.
"""
from __future__ import annotations

import logging
import uuid
from collections.abc import Sequence
from datetime import datetime, timedelta, timezone
from typing import Any

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from outreach_os.core.calendar_client import (
    CalendarClient,
    CalendarEvent,
    CalendarReceipt,
    generate_ics_uid,
    get_calendar_client,
)
from outreach_os.core.config import get_settings
from outreach_os.domain.models.lead import Lead
from outreach_os.domain.models.mailbox import Mailbox
from outreach_os.domain.models.meeting import Meeting

log = logging.getLogger(__name__)


class MeetingError(RuntimeError):
    pass


class MeetingService:
    def __init__(
        self,
        session: AsyncSession,
        calendar: CalendarClient | None = None,
    ) -> None:
        self.session = session
        self.calendar = calendar or get_calendar_client()
        self.settings = get_settings()

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    async def create_proposal(
        self,
        *,
        tenant_id: uuid.UUID,
        lead_id: uuid.UUID,
        send_id: uuid.UUID | None = None,
        reply_id: uuid.UUID | None = None,
        mailbox_id: uuid.UUID | None = None,
        subject: str | None = None,
        agenda: str | None = None,
        duration_minutes: int | None = None,
    ) -> Meeting:
        """Auto-propose a meeting. Generates 3 candidate slots within the
        next 5 working days (Mon-Fri, 10:00-16:00 local UTC, 30min apart
        by default). Returns the new Meeting in `proposed` status.
        """
        duration = duration_minutes or self.settings.meeting_default_duration_minutes
        lead = await self._load_lead(tenant_id, lead_id)
        organizer_email = await self._resolve_organizer_email(
            tenant_id, mailbox_id, fallback=lead.email
        )
        attendee_email = lead.email or organizer_email
        subj = subject or f"Quick chat with Outreach OS \u2014 {lead.full_name or lead.email or 'lead'}"
        # Default 3 slots, generated by `_propose_slots`.
        slots = self._propose_slots(duration_minutes=duration)
        meeting = Meeting(
            tenant_id=tenant_id,
            lead_id=lead.id,
            mailbox_id=mailbox_id,
            send_id=send_id,
            reply_id=reply_id,
            subject=subj,
            agenda=agenda or "Discovery call: learn about your goals and see if we're a fit.",
            location="Google Meet (link will be sent on confirmation)",
            duration_minutes=duration,
            proposed_slots=slots,
            status="proposed",
            ics_uid=generate_ics_uid(),
            organizer_email=organizer_email,
            attendee_email=attendee_email,
        )
        self.session.add(meeting)
        await self.session.flush()

        # Phase 6: surface the proposal as a notification.
        try:
            from outreach_os.services.notification_service import publish

            await publish(
                self.session,
                tenant_id=tenant_id,
                event_key="meeting.proposed",
                severity="info",
                title=f"Meeting proposed: {lead.email or lead.full_name or 'lead'}",
                body=meeting.subject,
                target_type="meeting",
                target_id=meeting.id,
                payload={
                    "lead_id": str(lead.id),
                    "duration_minutes": duration,
                    "slot_count": len(slots),
                },
            )
        except Exception:
            log.warning("notification dispatch failed for meeting proposal", exc_info=True)

        return meeting

    async def confirm(
        self,
        *,
        tenant_id: uuid.UUID,
        meeting_id: uuid.UUID,
        slot_index: int,
    ) -> Meeting:
        """Confirm the meeting on one of the proposed slots.

        Validates: meeting is in `proposed` status, slot_index is in range.
        Creates the calendar event (status=CONFIRMED), updates the meeting
        row with provider_event_id, chosen_slot, confirmed_at.
        """
        meeting = await self._load_meeting(tenant_id, meeting_id)
        if meeting.status != "proposed":
            raise MeetingError(
                f"cannot confirm meeting in status {meeting.status!r}"
            )
        if not (0 <= slot_index < len(meeting.proposed_slots)):
            raise MeetingError(
                f"slot_index {slot_index} out of range (have "
                f"{len(meeting.proposed_slots)} slots)"
            )
        slot = meeting.proposed_slots[slot_index]
        start = self._parse_slot_start(slot)
        end = self._parse_slot_end(slot, fallback_start=start,
                                   duration_minutes=meeting.duration_minutes)
        event = CalendarEvent(
            ics_uid=meeting.ics_uid,
            subject=meeting.subject,
            description=meeting.agenda,
            location=meeting.location,
            start=start,
            end=end,
            organizer_email=meeting.organizer_email,
            attendee_emails=[meeting.attendee_email],
            sequence=meeting.ics_sequence,
            status="CONFIRMED",
        )
        try:
            receipt: CalendarReceipt = self.calendar.create(event)
        except Exception as exc:
            log.exception("calendar create failed for meeting %s", meeting.id)
            raise MeetingError(f"calendar create failed: {exc}") from exc
        meeting.provider_event_id = receipt.provider_event_id
        meeting.ics_sequence += 1
        meeting.chosen_slot = start
        meeting.status = "confirmed"
        meeting.confirmed_at = datetime.now(timezone.utc)
        await self.session.flush()

        # Phase 6: surface confirmation.
        try:
            from outreach_os.services.notification_service import publish

            await publish(
                self.session,
                tenant_id=tenant_id,
                event_key="meeting.confirmed",
                severity="success",
                title=f"Meeting confirmed: {meeting.attendee_email}",
                body=f"{meeting.subject} \u2014 {start.isoformat()}",
                target_type="meeting",
                target_id=meeting.id,
                payload={
                    "provider_event_id": receipt.provider_event_id,
                    "start": start.isoformat(),
                },
            )
        except Exception:
            log.warning("notification dispatch failed for meeting confirm", exc_info=True)

        return meeting

    async def decline(
        self, *, tenant_id: uuid.UUID, meeting_id: uuid.UUID
    ) -> Meeting:
        meeting = await self._load_meeting(tenant_id, meeting_id)
        if meeting.status in ("declined", "cancelled", "completed"):
            raise MeetingError(
                f"cannot decline meeting in status {meeting.status!r}"
            )
        # If a calendar event was created, cancel it first.
        if meeting.provider_event_id:
            try:
                self.calendar.cancel(meeting.provider_event_id)
            except Exception:
                log.warning(
                    "calendar cancel failed for meeting %s (provider_event_id=%s)",
                    meeting.id, meeting.provider_event_id,
                    exc_info=True,
                )
        meeting.status = "declined"
        meeting.declined_at = datetime.now(timezone.utc)
        await self.session.flush()

        try:
            from outreach_os.services.notification_service import publish

            await publish(
                self.session,
                tenant_id=tenant_id,
                event_key="meeting.declined",
                severity="warning",
                title=f"Meeting declined: {meeting.attendee_email}",
                target_type="meeting",
                target_id=meeting.id,
            )
        except Exception:
            log.warning("notification dispatch failed for meeting decline", exc_info=True)

        return meeting

    async def cancel(
        self, *, tenant_id: uuid.UUID, meeting_id: uuid.UUID
    ) -> Meeting:
        meeting = await self._load_meeting(tenant_id, meeting_id)
        if meeting.status in ("cancelled", "completed"):
            raise MeetingError(
                f"cannot cancel meeting in status {meeting.status!r}"
            )
        if meeting.provider_event_id:
            try:
                self.calendar.cancel(meeting.provider_event_id)
            except Exception:
                log.warning(
                    "calendar cancel failed for meeting %s (provider_event_id=%s)",
                    meeting.id, meeting.provider_event_id,
                    exc_info=True,
                )
        meeting.status = "cancelled"
        meeting.cancelled_at = datetime.now(timezone.utc)
        await self.session.flush()

        try:
            from outreach_os.services.notification_service import publish

            await publish(
                self.session,
                tenant_id=tenant_id,
                event_key="meeting.cancelled",
                severity="warning",
                title=f"Meeting cancelled: {meeting.attendee_email}",
                target_type="meeting",
                target_id=meeting.id,
            )
        except Exception:
            log.warning("notification dispatch failed for meeting cancel", exc_info=True)

        return meeting

    async def get(
        self, *, tenant_id: uuid.UUID, meeting_id: uuid.UUID
    ) -> Meeting | None:
        return (
            await self.session.execute(
                select(Meeting).where(
                    Meeting.tenant_id == tenant_id, Meeting.id == meeting_id
                )
            )
        ).scalar_one_or_none()

    async def list_meetings(
        self,
        *,
        tenant_id: uuid.UUID,
        status: str | None = None,
        lead_id: uuid.UUID | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> tuple[Sequence[Meeting], int]:
        stmt = select(Meeting).where(Meeting.tenant_id == tenant_id)
        count_stmt = select(func.count()).select_from(Meeting).where(
            Meeting.tenant_id == tenant_id
        )
        if status:
            stmt = stmt.where(Meeting.status == status)
            count_stmt = count_stmt.where(Meeting.status == status)
        if lead_id:
            stmt = stmt.where(Meeting.lead_id == lead_id)
            count_stmt = count_stmt.where(Meeting.lead_id == lead_id)
        total = (await self.session.execute(count_stmt)).scalar_one()
        items = (
            await self.session.execute(
                stmt.order_by(Meeting.proposed_at.desc())
                .limit(limit).offset(offset)
            )
        ).scalars().all()
        return items, int(total)

    async def find_proposed_for_reply(
        self, *, tenant_id: uuid.UUID, reply_id: uuid.UUID
    ) -> Meeting | None:
        """Find an open (proposed) meeting triggered by this reply.

        Used by ReplyService on a counter-reply to detect "yes, Tuesday at
        2pm" and confirm the meeting without the user clicking a button.
        """
        return (
            await self.session.execute(
                select(Meeting).where(
                    Meeting.tenant_id == tenant_id,
                    Meeting.reply_id == reply_id,
                    Meeting.status == "proposed",
                )
            )
        ).scalar_one_or_none()

    async def find_proposed_for_lead(
        self, *, tenant_id: uuid.UUID, lead_id: uuid.UUID
    ) -> Meeting | None:
        """Find the most-recent open meeting for a lead (across all
        replies). Used by ReplyService on the FIRST positive reply to
        detect a counter-reply intent."""
        return (
            await self.session.execute(
                select(Meeting)
                .where(
                    Meeting.tenant_id == tenant_id,
                    Meeting.lead_id == lead_id,
                    Meeting.status == "proposed",
                )
                .order_by(Meeting.proposed_at.desc())
            )
        ).scalars().first()

    # ------------------------------------------------------------------ #
    # Internals
    # ------------------------------------------------------------------ #

    async def _load_lead(
        self, tenant_id: uuid.UUID, lead_id: uuid.UUID
    ) -> Lead:
        lead = (
            await self.session.execute(
                select(Lead).where(
                    Lead.tenant_id == tenant_id, Lead.id == lead_id
                )
            )
        ).scalar_one_or_none()
        if lead is None:
            raise MeetingError(f"lead {lead_id} not found for tenant {tenant_id}")
        return lead

    async def _load_meeting(
        self, tenant_id: uuid.UUID, meeting_id: uuid.UUID
    ) -> Meeting:
        meeting = await self.get(tenant_id=tenant_id, meeting_id=meeting_id)
        if meeting is None:
            raise MeetingError(f"meeting {meeting_id} not found for tenant {tenant_id}")
        return meeting

    async def _resolve_organizer_email(
        self,
        tenant_id: uuid.UUID,
        mailbox_id: uuid.UUID | None,
        fallback: str | None,
    ) -> str:
        """The organizer's email is the mailbox that sent the original
        campaign email. Falls back to the lead's email in tests where
        no mailbox is wired up."""
        if mailbox_id is not None:
            mb = (
                await self.session.execute(
                    select(Mailbox).where(
                        Mailbox.tenant_id == tenant_id, Mailbox.id == mailbox_id
                    )
                )
            ).scalar_one_or_none()
            if mb is not None:
                return mb.email_address
        if fallback:
            return fallback
        raise MeetingError(
            "could not resolve organizer email (no mailbox_id and lead has no email)"
        )

    def _propose_slots(
        self, *, duration_minutes: int = 30, count: int = 3
    ) -> list[dict[str, Any]]:
        """Generate `count` working-hour slots within the next 5 working
        days, spaced 1 day apart. Mon-Fri 10:00 UTC, 30min by default.

        Each slot dict has shape: {index, start, end} where start/end are
        ISO 8601 strings in UTC (timezone-aware).
        """
        from outreach_os.domain.schemas.phase5 import PROPOSED_SLOT_COUNT
        n = min(count, PROPOSED_SLOT_COUNT)
        now = datetime.now(timezone.utc)
        # Start from tomorrow at 10:00 UTC to avoid suggesting past times.
        candidate_day = (now + timedelta(days=1)).replace(
            hour=10, minute=0, second=0, microsecond=0
        )
        slots: list[dict[str, Any]] = []
        # Skip weekends by stepping +1 day until weekday <= 4.
        while len(slots) < n:
            if candidate_day.weekday() < 5:  # 0=Mon, 4=Fri
                start = candidate_day
                end = start + timedelta(minutes=duration_minutes)
                slots.append({
                    "index": len(slots),
                    "start": start.isoformat(),
                    "end": end.isoformat(),
                })
            candidate_day = candidate_day + timedelta(days=1)
        return slots

    @staticmethod
    def _parse_slot_start(slot: dict[str, Any]) -> datetime:
        start = slot.get("start")
        if not isinstance(start, str):
            raise MeetingError(f"slot missing start: {slot!r}")
        dt = datetime.fromisoformat(start)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt

    @staticmethod
    def _parse_slot_end(
        slot: dict[str, Any], *, fallback_start: datetime, duration_minutes: int
    ) -> datetime:
        end = slot.get("end")
        if isinstance(end, str):
            dt = datetime.fromisoformat(end)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            return dt
        return fallback_start + timedelta(minutes=duration_minutes)


__all__ = ["MeetingError", "MeetingService"]
